// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh3JlqvedHNXto6pGIOdUkTFXsO0dfqE4',
    appId: '1:1027153162918:web:4a074e946f1b1a11c4ba67',
    messagingSenderId: '1027153162918',
    projectId: 'opencj-6067a',
    authDomain: 'opencj-6067a.firebaseapp.com',
    storageBucket: 'opencj-6067a.firebasestorage.app',
    measurementId: 'G-R9JDSH3E18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuQ-pnLeqq29EW_w9jKeBOu3gJTmUu-u4',
    appId: '1:1027153162918:android:555aa9b2fca76b8ac4ba67',
    messagingSenderId: '1027153162918',
    projectId: 'opencj-6067a',
    storageBucket: 'opencj-6067a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyC4nMRpIg6HLe9AidrZ_jHQHKvCi2lQk',
    appId: '1:1027153162918:ios:e96eac892b9a3de6c4ba67',
    messagingSenderId: '1027153162918',
    projectId: 'opencj-6067a',
    storageBucket: 'opencj-6067a.firebasestorage.app',
    iosBundleId: 'com.example.opencjFe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyC4nMRpIg6HLe9AidrZ_jHQHKvCi2lQk',
    appId: '1:1027153162918:ios:e96eac892b9a3de6c4ba67',
    messagingSenderId: '1027153162918',
    projectId: 'opencj-6067a',
    storageBucket: 'opencj-6067a.firebasestorage.app',
    iosBundleId: 'com.example.opencjFe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh3JlqvedHNXto6pGIOdUkTFXsO0dfqE4',
    appId: '1:1027153162918:web:8410879bab926d32c4ba67',
    messagingSenderId: '1027153162918',
    projectId: 'opencj-6067a',
    authDomain: 'opencj-6067a.firebaseapp.com',
    storageBucket: 'opencj-6067a.firebasestorage.app',
    measurementId: 'G-0ZSYDQV3YC',
  );
}
